Exception ignored in: <function Local.__del__ at 0x7f89f7438c10>
Traceback (most recent call last):
  File "/home/manthan/home_server/venv/lib/python3.8/site-packages/asgiref/local.py", line 95, in __del__
NameError: name 'AttributeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7f89f7438c10>
Traceback (most recent call last):
  File "/home/manthan/home_server/venv/lib/python3.8/site-packages/asgiref/local.py", line 95, in __del__
NameError: name 'AttributeError' is not defined
